[[area]]
name = "default"
path = "./screen_capture"
prefix = "default_name_"
number = 0
start_x = 0
start_y = 0
width = 100
height = 200

[[area]]
name = "area2"
path = "./screen_capture"
prefix = "area2_name_"
number = 0
start_x = 111
start_y = 222
width = 333
height = 444

